# https://docs.readthedocs.io/en/stable/config-file/
version: 2

mkdocs:
  configuration: mkdocs.yml

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc